
FROM python:slim-buster

WORKDIR app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY *.py .

CMD ["/usr/local/bin/opentelemetry-instrument", "--service_name", "spammer", "--exporter_otlp_endpoint", "http://collector:4317", "python", "spammer.py"]
