extensions:
  basicauth/traces:
    client_auth:
      username: "180575"
      password: "${API_KEY}"

  basicauth/logs:
    client_auth:
      username: "184062"
      password: "${API_KEY}"

  basicauth/metrics:
    client_auth:
      username: "370184"
      password: "${API_KEY}"

processors:
  batch:

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
  otlp/gct:
    endpoint: tempo-us-central1.grafana.net:443
    auth:
      authenticator: basicauth/traces
  loki/gcl:
    endpoint: "https://logs-prod3.grafana.net/loki/api/v1/push"
    auth:
      authenticator: basicauth/logs
  prometheusremotewrite:
    endpoint: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    auth:
      authenticator: "basicauth/metrics"

service:
  extensions: [basicauth/traces, basicauth/logs, basicauth/metrics]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/gct]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki/gcl]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite]
